# This was generated by taking the examples from the community-mixins repo and
# then passing them through many layers of AI sloppery.
# I wanted to write this in Cue but it turns out building Cue from Nix isn't
# well supported because Cue doesn't have a first-class way to vendor or pin
# dependencies (I think vendoring might be possible but it's not documented).
# Anyway this is slop but it does work.
# It should be possible to deploy this without a full system update by
# evaluating this to JSON and then sending it via percli apply.
let
  mkPromQuery =
    { query, seriesNameFormat }:
    {
      kind = "TimeSeriesQuery";
      spec.plugin = {
        kind = "PrometheusTimeSeriesQuery";
        spec = {
          datasource = {
            kind = "PrometheusDatasource";
            name = "prometheus";
          };
          inherit query seriesNameFormat;
        };
      };
    };
  mkTSPanel =
    {
      name,
      description,
      queries,
      unit ? null,
      shortValues ? false,
    }:
    {
      kind = "Panel";
      spec = {
        display = { inherit name description; };
        plugin = {
          kind = "TimeSeriesChart";
          spec = {
            legend = {
              mode = "table";
              position = "bottom";
              values = [ "last" ];
            };
          }
          // (
            if unit != null then
              {
                yAxis.format = {
                  inherit unit;
                }
                // (if shortValues then { inherit shortValues; } else { });
              }
            else
              { }
          );
        };
        inherit queries;
      };
    };
  mkGrid =
    { title, panels }:
    {
      kind = "Grid";
      spec = {
        display.title = title;
        items = map (p: {
          x = p.x;
          y = 0;
          width = 12;
          height = 8;
          content."$ref" = "#/spec/panels/${p.ref}";
        }) panels;
      };
    };
in
{
  kind = "Dashboard";
  metadata = {
    name = "node-exporter-nodes";
    createdAt = "0001-01-01T00:00:00Z";
    project = "homelab";
    updatedAt = "0001-01-01T00:00:00Z";
    version = 0;
  };
  spec = {
    display.name = "Node Exporter / Nodes";
    duration = "1h";
    variables = [
      {
        kind = "ListVariable";
        spec = {
          name = "instance";
          display = {
            name = "instance";
            hidden = false;
          };
          allowAllValue = true;
          allowMultiple = false;
          plugin = {
            kind = "PrometheusLabelValuesVariable";
            spec = {
              datasource = {
                kind = "PrometheusDatasource";
                name = "prometheus";
              };
              labelName = "instance";
              matchers = [ ''node_uname_info{job="node",sysname!="Darwin"}'' ];
            };
          };
        };
      }
    ];

    panels = {
      "0_0" = mkTSPanel {
        name = "CPU Usage";
        description = "Shows CPU utilization percentage across cluster nodes";
        unit = "percent-decimal";
        queries = [
          (mkPromQuery {
            query = ''
              1 - sum without (mode) (
                rate(node_cpu_seconds_total{instance="$instance",job="node",mode=~"idle|iowait|steal"}[$__rate_interval])
              )
              / ignoring (cpu) group_left ()
              count without (cpu, mode) (node_cpu_seconds_total{instance="$instance",job="node",mode="idle"})
            '';
            seriesNameFormat = "{{device}} - CPU - Usage";
          })
        ];
      };
      "0_1" = mkTSPanel {
        name = "CPU Usage";
        description = "Shows CPU utilization metrics";
        queries = [
          (mkPromQuery {
            query = ''node_load1{instance="$instance",job="node"}'';
            seriesNameFormat = "CPU - 1m Average";
          })
          (mkPromQuery {
            query = ''node_load5{instance="$instance",job="node"}'';
            seriesNameFormat = "CPU - 5m Average";
          })
          (mkPromQuery {
            query = ''node_load15{instance="$instance",job="node"}'';
            seriesNameFormat = "CPU - 15m Average";
          })
          (mkPromQuery {
            query = ''count(node_cpu_seconds_total{instance="$instance",job="node",mode="idle"})'';
            seriesNameFormat = "CPU - Logical Cores";
          })
        ];
      };
      "1_0" = mkTSPanel {
        name = "Memory Usage";
        description = "Shows memory utilization metrics";
        unit = "bytes";
        shortValues = true;
        queries = [
          (mkPromQuery {
            query = ''node_memory_Buffers_bytes{instance="$instance",job="node"}'';
            seriesNameFormat = "Memory - Buffers";
          })
          (mkPromQuery {
            query = ''node_memory_Cached_bytes{instance="$instance",job="node"}'';
            seriesNameFormat = "Memory - Cached";
          })
          (mkPromQuery {
            query = ''node_memory_MemFree_bytes{instance="$instance",job="node"}'';
            seriesNameFormat = "Memory - Free";
          })
        ];
      };
      "1_1" = {
        kind = "Panel";
        spec = {
          display = {
            name = "Memory Usage";
            description = "Shows memory utilization across nodes";
          };
          plugin = {
            kind = "GaugeChart";
            spec = {
              calculation = "last";
              format.unit = "percent";
              thresholds = {
                mode = "absolute";
                defaultColor = "green";
                steps = [
                  {
                    value = 80;
                    color = "orange";
                  }
                  {
                    value = 90;
                    color = "red";
                  }
                ];
              };
            };
          };
          queries = [
            (mkPromQuery {
              query = ''
                100 - avg(node_memory_MemAvailable_bytes{instance="$instance",job="node"})
                / avg(node_memory_MemTotal_bytes{instance="$instance",job="node"}) * 100
              '';
              seriesNameFormat = "Memory - Usage";
            })
          ];
        };
      };
      "2_0" = mkTSPanel {
        name = "Disk I/O Bytes";
        description = "Shows disk I/O metrics in bytes";
        unit = "bytes";
        queries = [
          (mkPromQuery {
            query = ''rate(node_disk_read_bytes_total{device!="",instance="$instance",job="node"}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Disk - Usage";
          })
          (mkPromQuery {
            query = ''rate(node_disk_io_time_seconds_total{device!="",instance="$instance",job="node"}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Disk - Written";
          })
        ];
      };
      "2_1" = mkTSPanel {
        name = "Disk I/O Seconds";
        description = "Shows disk I/O duration metrics";
        unit = "seconds";
        queries = [
          (mkPromQuery {
            query = ''rate(node_disk_io_time_seconds_total{device!="",instance="$instance",job="node"}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Disk - IO Time";
          })
        ];
      };
      "3_0" = mkTSPanel {
        name = "Network Received";
        description = "Shows network received bytes metrics";
        unit = "bytes/sec";
        queries = [
          (mkPromQuery {
            query = ''rate(node_network_receive_bytes_total{device!="lo",instance="$instance",job="node"}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Network - Received";
          })
        ];
      };
      "3_1" = mkTSPanel {
        name = "Network Transmitted";
        description = "Shows network transmitted bytes metrics";
        unit = "bytes/sec";
        queries = [
          (mkPromQuery {
            query = ''rate(node_network_receive_bytes_total{device!="lo",instance="$instance",job="node"}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Network - Transmitted";
          })
        ];
      };
    };

    layouts = [
      (mkGrid {
        title = "CPU";
        panels = [
          {
            x = 0;
            ref = "0_0";
          }
          {
            x = 12;
            ref = "0_1";
          }
        ];
      })
      (mkGrid {
        title = "Memory";
        panels = [
          {
            x = 0;
            ref = "1_0";
          }
          {
            x = 12;
            ref = "1_1";
          }
        ];
      })
      (mkGrid {
        title = "Disk";
        panels = [
          {
            x = 0;
            ref = "2_0";
          }
          {
            x = 12;
            ref = "2_1";
          }
        ];
      })
      (mkGrid {
        title = "Network";
        panels = [
          {
            x = 0;
            ref = "3_0";
          }
          {
            x = 12;
            ref = "3_1";
          }
        ];
      })
    ];
  };
}
