# This was generated by taking the examples from the community-mixins repo and
# then passing them through many layers of AI sloppery.
# I wanted to write this in Cue but it turns out building Cue from Nix isn't
# well supported because Cue doesn't have a first-class way to vendor or pin
# dependencies (I think vendoring might be possible but it's not documented).
# Anyway this is slop but it does work.
# It should be possible to deploy this without a full system update by
# evaluating this to JSON and then sending it via percli apply.
let
  lib = import ./lib.nix;
  # Filter to data coming from the node-exporter scrape jobs.
  jobFilter = ''job=~"node_.*"'';
  # Filter to data for the selected instance (in this case that means a node).
  instanceFilter = ''instance="$instance",${jobFilter}'';
in
{
  kind = "Dashboard";
  metadata = {
    name = "node-exporter-nodes";
    project = "homelab";
    version = 0;
  };
  spec = {
    display.name = "Node Exporter / Nodes";
    duration = "1h";
    variables = [
      {
        kind = "ListVariable";
        spec = {
          name = "instance";
          display = {
            name = "instance";
            hidden = false;
          };
          allowAllValue = true;
          allowMultiple = false;
          plugin = {
            kind = "PrometheusLabelValuesVariable";
            spec = {
              datasource = {
                kind = "PrometheusDatasource";
                name = "prometheus";
              };
              labelName = "instance";
              matchers = [ ''node_uname_info{${jobFilter},sysname!="Darwin"}'' ];
            };
          };
        };
      }
    ];

    panels = {
      "0_0" = lib.mkTSPanel {
        name = "CPU Usage";
        description = "Shows CPU utilization metrics";
        queries = [
          (lib.mkPromQuery {
            query = "node_load1{${instanceFilter}}";
            seriesNameFormat = "CPU - 1m Average";
          })
          (lib.mkPromQuery {
            query = "node_load5{${instanceFilter}}";
            seriesNameFormat = "CPU - 5m Average";
          })
          (lib.mkPromQuery {
            query = "node_load15{${instanceFilter}}";
            seriesNameFormat = "CPU - 15m Average";
          })
          (lib.mkPromQuery {
            query = ''count(node_cpu_seconds_total{${instanceFilter},mode="idle"})'';
            seriesNameFormat = "CPU - Logical Cores";
          })
        ];
      };
      "1_0" = lib.mkTSPanel {
        name = "Memory Usage";
        description = "Shows memory utilization metrics";
        unit = "bytes";
        shortValues = true;
        queries = [
          (lib.mkPromQuery {
            query = "node_memory_MemFree_bytes{${instanceFilter}}";
            seriesNameFormat = "Memory - Free";
          })
          (lib.mkPromQuery {
            query = "node_memory_Buffers_bytes{${instanceFilter}}";
            seriesNameFormat = "Memory - Buffers";
          })
          (lib.mkPromQuery {
            query = "node_memory_Cached_bytes{${instanceFilter}}";
            seriesNameFormat = "Memory - Cached";
          })
          (lib.mkPromQuery {
            query = "node_memory_Slab_bytes{${instanceFilter}}";
            seriesNameFormat = "Memory - Slab";
          })
        ];
      };
      "1_1" = {
        kind = "Panel";
        spec = {
          display = {
            name = "Memory Usage";
            description = "Shows memory utilization across nodes";
          };
          plugin = {
            kind = "GaugeChart";
            spec = {
              calculation = "last";
              format.unit = "percent";
              thresholds = {
                mode = "absolute";
                defaultColor = "green";
                steps = [
                  {
                    value = 80;
                    color = "orange";
                  }
                  {
                    value = 90;
                    color = "red";
                  }
                ];
              };
            };
          };
          queries = [
            (lib.mkPromQuery {
              query = ''
                100 - avg(node_memory_MemAvailable_bytes{${instanceFilter}})
                / avg(node_memory_MemTotal_bytes{${instanceFilter}}) * 100
              '';
              seriesNameFormat = "Memory - Usage";
            })
          ];
        };
      };
      "2_0" = lib.mkTSPanel {
        name = "Disk I/O Bytes";
        description = "Shows disk I/O metrics in bytes";
        unit = "bytes";
        queries = [
          (lib.mkPromQuery {
            query = ''rate(node_disk_read_bytes_total{device!="",${instanceFilter}}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Disk - Usage";
          })
          (lib.mkPromQuery {
            query = ''rate(node_disk_io_time_seconds_total{device!="",${instanceFilter}}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Disk - Written";
          })
        ];
      };
      "2_1" = lib.mkTSPanel {
        name = "Disk I/O Seconds";
        description = "Shows disk I/O duration metrics";
        unit = "seconds";
        queries = [
          (lib.mkPromQuery {
            query = ''rate(node_disk_io_time_seconds_total{device!="",${instanceFilter}}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Disk - IO Time";
          })
        ];
      };
      "3_0" = lib.mkTSPanel {
        name = "Network Received";
        description = "Shows network received bytes metrics";
        unit = "bytes/sec";
        queries = [
          (lib.mkPromQuery {
            query = ''rate(node_network_receive_bytes_total{device!="lo",${instanceFilter}}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Network - Received";
          })
        ];
      };
      "3_1" = lib.mkTSPanel {
        name = "Network Transmitted";
        description = "Shows network transmitted bytes metrics";
        unit = "bytes/sec";
        queries = [
          (lib.mkPromQuery {
            query = ''rate(node_network_receive_bytes_total{device!="lo",${instanceFilter}}[$__rate_interval])'';
            seriesNameFormat = "{{device}} - Network - Transmitted";
          })
        ];
      };
    };

    layouts = [
      (lib.mkGrid {
        title = "CPU";
        panels = [
          {
            x = 0;
            ref = "0_0";
          }
        ];
      })
      (lib.mkGrid {
        title = "Memory";
        panels = [
          {
            x = 0;
            ref = "1_0";
          }
          {
            x = 12;
            ref = "1_1";
          }
        ];
      })
      (lib.mkGrid {
        title = "Disk";
        panels = [
          {
            x = 0;
            ref = "2_0";
          }
          {
            x = 12;
            ref = "2_1";
          }
        ];
      })
      (lib.mkGrid {
        title = "Network";
        panels = [
          {
            x = 0;
            ref = "3_0";
          }
          {
            x = 12;
            ref = "3_1";
          }
        ];
      })
    ];
  };
}
