# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cf4ababf-37ac-4d54-943c-a9363b2572d3";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b88d80b3-ff99-4ba1-9079-59dcff93e336".device =
    "/dev/disk/by-uuid/b88d80b3-ff99-4ba1-9079-59dcff93e336";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2092-0AE7";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/b2445134-327f-42b9-b1b4-dbd9c72fcae0"; } ];

}
