// Package probe defines the capabilities an agent may invoke on a homelab host
// and the request that invokes one. The manifest is generated by Nix from
// nixos_modules/slop-probe.nix, so the set of things an agent can do to a host
// is reviewed as a diff and deployed with the rest of the config. See
// design_docs/agent_prod_access.md.
package probe

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Option is one parameter of a probe. An option with no RegexpPattern is a
// switch, which the caller either passes or doesn't; anything else takes a
// value, and the value must match RegexpPattern in its entirety.
type Option struct {
	Description string `json:"description"`
	// Flag the value is passed as, e.g. "--unit". Empty makes the option
	// positional, in which case Position orders it against the others.
	Flag          string `json:"flag"`
	Position      int    `json:"position"`
	RegexpPattern string `json:"regexpPattern"`
	Required      bool   `json:"required"`
}

// IsSwitch reports whether the option is a valueless flag.
func (o Option) IsSwitch() bool { return o.RegexpPattern == "" }

type Probe struct {
	Description string `json:"description"`
	// Command is an absolute path, executed directly: no shell is involved on
	// either side of the connection.
	Command  string            `json:"command"`
	Args     []string          `json:"args"`
	Options  map[string]Option `json:"options"`
	MaxBytes int64             `json:"maxBytes"`
	Timeout  int               `json:"timeoutSeconds"`
}

type Manifest struct {
	Host   string           `json:"host"`
	Probes map[string]Probe `json:"probes"`
}

// Request is what the client sends on stdin. A switch is represented by an
// empty value.
type Request struct {
	Probe   string            `json:"probe"`
	Options map[string]string `json:"options"`
}

// ListProbe is served by the server itself rather than declared in the
// manifest, so that every host can describe itself.
const ListProbe = "list"

func LoadManifest(path string) (*Manifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var m Manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("parsing manifest %s: %w", path, err)
	}
	for name, p := range m.Probes {
		// Nothing resolves the command through PATH, so a relative one would
		// be interpreted against whatever directory the server happens to be
		// sitting in.
		if !filepath.IsAbs(p.Command) {
			return nil, fmt.Errorf("probe %q command %q is not an absolute path", name, p.Command)
		}
		for optName, opt := range p.Options {
			if opt.IsSwitch() {
				continue
			}
			if _, err := compile(opt.RegexpPattern); err != nil {
				return nil, fmt.Errorf("probe %q option %q: %w", name, optName, err)
			}
		}
	}
	return &m, nil
}

// compile anchors a pattern at both ends, so that an option can't be satisfied
// by a value that merely contains something allowable. \A and \z are the start
// and end of the text; ^ and $ would mean the same by default, but a pattern is
// free to turn on multi-line mode, which would make those match at every
// newline instead. The (?:) keeps a top-level alternation in the pattern from
// escaping the anchors.
func compile(pattern string) (*regexp.Regexp, error) {
	return regexp.Compile(`\A(?:` + pattern + `)\z`)
}

// Argv renders a validated command line. Every value is checked against the
// option's pattern first, and unknown options are an error rather than being
// dropped: an agent that misremembers a flag should be told so, not handed
// output that quietly answers a different question.
func (p Probe) Argv(options map[string]string) ([]string, error) {
	for name, value := range options {
		opt, ok := p.Options[name]
		if !ok {
			return nil, fmt.Errorf("unknown option %q, want one of %s", name, strings.Join(p.optionNames(), ", "))
		}
		switch {
		case opt.IsSwitch() && value != "":
			return nil, fmt.Errorf("option %q is a switch and takes no value", name)
		case !opt.IsSwitch() && value == "":
			return nil, fmt.Errorf("option %q needs a value", name)
		}
		if opt.IsSwitch() {
			continue
		}
		pattern, err := compile(opt.RegexpPattern)
		if err != nil {
			return nil, fmt.Errorf("option %q: %w", name, err)
		}
		if !pattern.MatchString(value) {
			return nil, fmt.Errorf("option %q value %q is not allowed here, it must match %s", name, value, opt.RegexpPattern)
		}
	}
	for name, opt := range p.Options {
		if _, ok := options[name]; opt.Required && !ok {
			return nil, fmt.Errorf("option %q is required", name)
		}
	}

	var flags, positional []string
	for _, name := range sortedKeys(options) {
		opt := p.Options[name]
		if opt.Flag == "" {
			continue
		}
		if opt.IsSwitch() {
			flags = append(flags, opt.Flag)
		} else if strings.HasPrefix(opt.Flag, "--") {
			flags = append(flags, opt.Flag+"="+options[name])
		} else {
			flags = append(flags, opt.Flag, options[name])
		}
	}
	for _, name := range p.positionalOrder() {
		if value, ok := options[name]; ok {
			positional = append(positional, value)
		}
	}

	argv := append([]string{p.Command}, p.Args...)
	argv = append(argv, flags...)
	return append(argv, positional...), nil
}

func (p Probe) optionNames() []string { return sortedKeys(p.Options) }

// positionalOrder is by declared Position, so that a probe wrapping something
// like `nix store diff-closures from to` can say which is which.
func (p Probe) positionalOrder() []string {
	var names []string
	for name, opt := range p.Options {
		if opt.Flag == "" {
			names = append(names, name)
		}
	}
	sort.Slice(names, func(i, j int) bool {
		a, b := p.Options[names[i]], p.Options[names[j]]
		if a.Position != b.Position {
			return a.Position < b.Position
		}
		return names[i] < names[j]
	})
	return names
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
