# TVHeadend as the IPTV backend for Jellyfin. It joins the Init7 multicast,
# demuxes each service per its PMT, and re-streams a clean single-program TS to
# Jellyfin over HTTP -- dropping the junk SCTE-35/data PIDs that make Jellyfin
# mis-probe the raw multicast (see iptv.nix for the full diagnosis). Jellyfin's
# M3U tuner then points at TVHeadend's /playlist/channels.m3u instead of the raw
# udp:// groups.
#
# Config model: TVHeadend owns its config in a persisted /var/lib/tvheadend. We
# seed exactly one thing declaratively -- an "IPTV Automatic Network" pointed at
# the init7.m3u we already generate (iptv.nix) -- and TVHeadend auto-creates the
# muxes/services/channels from it. We seed only if absent, so TVHeadend's own
# runtime state (channel maps, EPG) survives reboots. Plain-JSON network config
# loads fine, but muxes can't be seeded as plain JSON (TVHeadend stores them in
# its own gzip format), which is exactly why we drive it from the auto-network
# rather than seeding muxes ourselves.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  configDir = "/var/lib/tvheadend";
  httpPort = 9981;
  htspPort = 9982;
  # The M3U generated by the init7-playlist service in iptv.nix.
  m3u = "/var/lib/jellyfin-iptv/init7.m3u";

  # Stable UUID so the seed-if-absent check below is idempotent across boots.
  netUuid = builtins.hashString "md5" "init7-auto-network";
  netConfig = builtins.toJSON {
    networkname = "Init7";
    url = "file://${m3u}";
    # Create a bouquet, which auto-maps the discovered services to channels --
    # Jellyfin needs channels to exist (it pulls /playlist/channels.m3u).
    bouquet = true;
    max_streams = 4;
    scan_create = true;
    skipinitscan = false;
  };
  seedNetwork = pkgs.writeShellApplication {
    name = "tvheadend-seed-network";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      net="${configDir}/input/iptv/networks/${netUuid}"
      # Seed once; thereafter TVHeadend owns the config (it's persisted).
      if [ ! -e "$net/config" ]; then
        mkdir -p "$net/muxes"
        printf '%s' '${netConfig}' > "$net/config"
      fi
    '';
  };

  # The auto-network discovers muxes/services from the M3U, but its bouquet
  # option doesn't actually map those services to channels (tested: 242
  # services, 0 channels). Jellyfin pulls /playlist/channels.m3u, so it needs
  # channels to exist. Map them ourselves via the service mapper API. Runs every
  # boot and is idempotent (already-mapped services are left as-is, no
  # duplicates), so it self-heals if the persisted state is ever lost.
  mapChannels = pkgs.writeShellApplication {
    name = "tvheadend-map-channels";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
    ];
    text = ''
      api="http://127.0.0.1:${toString httpPort}"

      # Wait for the HTTP API to come up.
      for _ in $(seq 1 60); do
        if curl -sf "$api/api/serverinfo" >/dev/null; then break; fi
        sleep 2
      done

      # Wait for the auto-network scan to discover services, and for that count
      # to stop growing, so we map the full set rather than an early subset.
      prev=-1
      for _ in $(seq 1 60); do
        n=$(curl -sf "$api/api/mpegts/service/grid?limit=1" | jq -r '.total // 0')
        if [ "$n" -gt 0 ] && [ "$n" = "$prev" ]; then break; fi
        prev=$n
        sleep 5
      done

      # Map every discovered service. check_availability=false maps without
      # subscribing (fast, includes momentarily-idle services); encrypted=true
      # ignores the encryption flag so nothing is skipped.
      services=$(curl -sf "$api/api/mpegts/service/grid?limit=100000" | jq -c '[.entries[].uuid]')
      node=$(jq -cn --argjson s "$services" \
        '{services: $s, check_availability: false, encrypted: true, merge_same_name: false}')
      curl -sf "$api/api/service/mapper/save" --data-urlencode "node=$node" >/dev/null
    '';
  };
in
{
  users.users.tvheadend = {
    isSystemUser = true;
    group = "tvheadend";
    home = configDir;
  };
  users.groups.tvheadend = { };

  # Persist TVHeadend's config + state (channel maps, EPG cache, DVR).
  bjackman.impermanence.extraPersistence.directories = [ configDir ];

  systemd.services.tvheadend = {
    description = "TVHeadend IPTV backend for Jellyfin";
    # Needs the network up to join the multicast, and init7.m3u to exist before
    # the first scan (init7-playlist is the oneshot that generates it).
    after = [
      "network-online.target"
      "init7-playlist.service"
    ];
    wants = [
      "network-online.target"
      "init7-playlist.service"
    ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStartPre = lib.getExe seedNetwork;
      # --noacl: no auth. The server binds to localhost and only Jellyfin (same
      # host) talks to it, so access control would just be friction.
      ExecStart = "${pkgs.bjackman.tvheadend}/bin/tvheadend -c ${configDir} --noacl -b 127.0.0.1 --http_port ${toString httpPort} --htsp_port ${toString htspPort}";
      User = "tvheadend";
      Group = "tvheadend";
      StateDirectory = "tvheadend";
      Restart = "on-failure";
      RestartSec = "5s";
    };
  };

  systemd.services.tvheadend-map-channels = {
    description = "Map TVHeadend services to channels for Jellyfin";
    after = [ "tvheadend.service" ];
    requires = [ "tvheadend.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = lib.getExe mapChannels;
      User = "tvheadend";
      Group = "tvheadend";
    };
  };
}
