# This is a configuration file that the `agenix` CLI (provided by this repo's
# devShell) reads if you are running it from this directory. It informs how
# files are encrypted.
let
  chungito = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMaakNfELyvjLLCRwH2U/yQ35HkEW+hEShAD7sn0mCmH brendan@chungito";
  fw13 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK8GAbvAbJljzHXALqbG5t0oolXkwSE00r+2qfxubEEF brendan@fw13";
  hostKeys = import ./host-keys.nix;
  all = [
    chungito
    hostKeys.chungito
    fw13
    hostKeys.fw13
    hostKeys.pizza
    hostKeys.norte
  ];
in
{
  # This is the password for the 'admin' user, configured via the PiKVM UI or
  # something I can't remember.
  "eadbald-pikvm-password.age".publicKeys = all;
  # Password for Jellyfin admin account
  "jellyfin-admin-password.age".publicKeys = all;
  # Contains an API key for Jellyfin. From the Jellarr docs I am not really sure
  # how you are supposed to generate this. In the end, I did it by running
  # Jellyfin, generating one in the UI, and copying it from there.
  "jellarr-api-key.age".publicKeys = all;
  # The same key again, but now in the form JELLARR_API_KEY=<key> because that's
  # how you have to provide it to Jellarr via its environmentFile option
  # (because it's been designed with sops-nix in mind).
  "jellarr-env.age".publicKeys = all;
  # Contains a JSON object of the form { "rpc-password": "{asfjdsakl.H" }.
  # The value is the hash of password for the Transmission daemon. To generate
  # the hash, I wrote it into the settings.json manually and then restarted the
  # service. The transmission edits the settings file lol.
  "transmission-rpc-password.json.age".publicKeys = all;
  # This is the raw hash for my user in transmission. I believe this was the
  # value I wrote into the JSON file in the step described above.
  "transmission-password.age".publicKeys = all;
  # This is a weak password so encrypt it instead of just checking in the salted
  # hash. Ideally I'd prefer to limit this to only being available to
  # hostKeys.chungito. However unfortunately agenix just has a single rekey
  # procedure that applies to all secrets, which means if there's a secret in
  # here that your current SSH key can't decrypt, the process fails.
  # I can't be bothered to figure out how to modularise the secrets just now
  # so, fuck it, anyone can decrypt this shit. (At least on devices I own).
  "weak-local-password-hash.age".publicKeys = all;
  # Authelia secrets generated with openssl rand  -base64 64 | agenix -e <file>
  "authelia/jwt-secret.age".publicKeys = all;
  "authelia/storage-encryption-key.age".publicKeys = all;
  "authelia/session-secret.age".publicKeys = all;
  "authelia/passwords.json.age".publicKeys = all;
  "authelia/hmac-secret.age".publicKeys = all;
  # nix run nixpkgs#authelia -- crypto pair rsa generate && agenix -e authelia/oidc-priv.pem.age < private.pem && rm private.pem
  "authelia/oidc-priv.pem.age".publicKeys = all;
  # The below generates the plaintext secret ("Random Password") and a hash
  # ("Digest").
  # nix run nixpkgs#authelia -- crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
  # echo -n $RANDOM_PASSWORD | agenix -e authelia/perses-client-secret.age
  # echo -n '<HASH>' | agenix -e authelia/perses-client-secret-hash.age
  "authelia/perses-client-secret.age".publicKeys = all;
  "authelia/perses-client-secret-hash.age".publicKeys = all;
  "authelia/jellyfin-client-secret.age".publicKeys = all;
  "authelia/jellyfin-client-secret-hash.age".publicKeys = all;
  "cloudflare-dns-api-token.age".publicKeys = all;
  # nix run nixpkgs#openssl -- rand -base64 12 | agenix -e filebrowser-samba-password.age
  "filebrowser-samba-password.age".publicKeys = all;
  "media-samba-password.age".publicKeys = all;
  "alertmanager-gmail-password.age".publicKeys = all;
  # nix run nixpkgs#openssl -- rand 32 | agenix -e perses-encryption-key.age
  "perses-encryption-key.age".publicKeys = all;
  # This was generated by Radarr the first time I ran it, I extracted it from
  #  /var/lib/radarr/.config/Radarr/config.xml
  "arr-api-key.age".publicKeys = all;
  "gemini-api-key.age".publicKeys = all;
  "brendan-sftp-privkey.age".publicKeys = all;
  # Deploy key with write access to github.com/bjackman/boxen, used by
  # github-mirror.service on pizza. Generated with:
  # ssh-keygen -t ed25519 -C github-mirror@pizza -f key && agenix -e github-mirror-privkey.age < key
  "github-mirror-privkey.age".publicKeys = all;
  # Password for brendan.jackman@linux.dev on https://webmail.migadu.com/. This
  # is also the IMAP and SMTP password.
  "migadu-linuxdev-password.age".publicKeys = all;
  # Forgejo credentials for the agent workflow. See design_docs/agent_prs.md.
  #
  # slopbot is the identity agents push and comment as. Both of these live in
  # the agent VM as well as on pizza, hence the extra recipient.
  # ssh-keygen -t ed25519 -C slopbot@gerrit -f key && agenix -e slopbot-ssh-privkey.age < key
  "slopbot-ssh-privkey.age".publicKeys = all ++ [ hostKeys.slopbox ];
  # The key slop-probe connects to the homelab with. See
  # design_docs/agent_prod_access.md. Only the agent VM uses it, and the hosts
  # it reaches need nothing but the public half, so this doesn't go to `all`.
  # ssh-keygen -t ed25519 -C slopbot@probe -f key && agenix -e slopbot-probe-ssh-privkey.age < key
  "slopbot-probe-ssh-privkey.age".publicKeys = [
    chungito
    fw13
    hostKeys.slopbox
  ];
  # slopbot's Authelia password, which is how the agent authenticates to
  # anything behind the proxy - Gerrit's REST API today. The hash of it lives
  # in authelia/passwords.json.age; this is the plaintext for the agent.
  # Generated by the add-user script.
  "slopbot-authelia-password.age".publicKeys = all ++ [ hostKeys.slopbox ];
}
